### ISSUE TITLE
Add `localhost` to the Trusted Hosts

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/uds-identity-config#115]
### Is your feature request related to a problem? Please describe.

As Ezra I want to be able to have clients that are CLIs interact with Keycloak to get OIDC tokens so that I can login to these CLIs with my SSO credentials

### Describe the solution you'd like

- **Given** I have a CLI application (like Cosign) that I want to login to
- **When** I run the action that requires login
- **Then** I am redirected to `sso.<domain>`
- **And When** I login
- **Then** I am redirected back to `localhost`
- **And** the CLI app receives the token

### Describe alternatives you've considered

We could not do this and instead implement other connectors to interface with Keycloak instead.

### Additional context

This is an enabler of: https://github.com/defenseunicorns/uds-core/issues/509

**Comment by bburky** [comment]
I talked to @Racer159 and the use case is local (cli) apps logging into Keycloak to get a JWT. Specifically sigstore cosign/gitsign. The browser redirect flow involves eventually redirecting to `http://localhost:(randomport)/jwt-whatever`. I would point out that this does require listening on a localhost port, which some restrictive firewalls may actually block

I would instead recommend using the OIDC device flow for this type of use case. It involves providing a random code to the user, the opens a browser and pasting in the code, and the app getting the JWT back (I think it polls keycloak until auth completes).

The device flow is supported by the sigstore apps and is also usable by tools like [`step oauth`](https://smallstep.com/docs/step-cli/reference/oauth/).

The redirect flow is fine if we really need it. Instead of localhost, it's preferable to redirect to a custom url scheme, this is many real desktop apps do.
