### ISSUE TITLE
Increase the "ssoSessionIdleTimeout" to 15 mins

### ISSUE THREAD

**Issue by brianrexrode** [defenseunicorns/uds-identity-config#188]
### Is your feature request related to a problem? Please describe.
Change the "ssoSessionIdleTimeout" from 600 secs to 900 secs which would still conform to:
V-222389: “Design and configure the application to terminate the non-privileged users session after 15 minutes of inactivity”

### Describe the solution you'd like

- Using uds-core keycloak deployment
- when a user session is idle for 15 mins
- Then keycloak will automatically expire that user's token and require a new login/token

### Describe alternatives you've considered
I configure and maintain my own identity-config image that changes that value
Manually update the value after uds-core keycloak deployment

**Comment by mjnagel** [comment]
@brianrexrode Looking back at the [previous context](https://github.com/defenseunicorns/uds-identity-config/issues/140) for when we updated these timeouts, looks like their were two timeout STIG rules being considered:
- [Non-privileged users](https://www.stigviewer.com/stig/application_security_and_development/2023-06-08/finding/V-222389): As you rightly point out, that rule only requires 15 minutes
- [Admin users](https://www.stigviewer.com/stig/application_security_and_development/2023-06-08/finding/V-222390): This one requires 10 minutes

The previous issue/PR went with the more conservative timeout to cover both cases since (in a given realm) Keycloak only allows a single timeout setting. Obviously for the Keycloak Admin/Master realm we could set this timeout differently, but this doesn't cover application admins (which I think is the focus of the linked STIG).

Is the ask for increasing this primarily for general usability? We can definitely make sure we're interpreting the STIG correctly, but want to make sure we aren't reducing any STIG compliance here as an effect.

**Comment by brianrexrode** [comment]
Ah, I definitely missed the admin user requirements. My ask is mostly focused on Mission App user timeouts which we could define in the client. Is that something that could be exposed as part of the operator creation of the client?

**Comment by mjnagel** [comment]
@brianrexrode do you know how to do that in the UI when making a client (or just an example client I could see from an export)? Trying to figure out what the per client timeouts look like and whether we could do that with our current API call.

**Comment by UnicornChance** [comment]
@brianrexrode will capture this functionality in this https://github.com/defenseunicorns/uds-core/pull/676. adding the client timeout session attribute to the allowed attributes
